# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('subject', models.CharField(max_length=225)),
                ('message', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
    ]
