# Generated by Django 2.0.4 on 2018-05-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180529_0533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailevent',
            options={'permissions': (('add_detail_highlight', 'Can add detail highlight'), ('change_detail_highlight', 'Can change detail highlight'), ('delete_detail_highlight', 'Can delete detail highlight'))},
        ),
        migrations.AlterModelOptions(
            name='eventgalery',
            options={'permissions': (('add_highlight', 'Can add highlight'), ('change_highlight', 'Can change highlight'), ('delete_highlight', 'Can delete highlight'))},
        ),
    ]
