# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/galery')),
                ('status', models.BooleanField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awardsgalery_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awardsgalery_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'awards_galery',
            },
        ),
        migrations.CreateModel(
            name='DetailGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/detail_galery')),
                ('caption', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.BooleanField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('AwardsGalery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.AwardsGalery')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailgalery_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailgalery_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detail_galery',
            },
        ),
    ]
