# Generated by Django 2.0.4 on 2018-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsgalery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/galery'),
        ),
        migrations.AlterField(
            model_name='detailgalery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/detail_galery'),
        ),
    ]
