# Generated by Django 2.0.4 on 2018-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20180508_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsgalery',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
