# Generated by Django 2.0.4 on 2018-05-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailWhatsnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/images/detail_galery')),
                ('caption', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.BooleanField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detailwhatsnew_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detailwhatsnew_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detail_whatsnew',
            },
        ),
        migrations.CreateModel(
            name='Whatsnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='static/images/galery')),
                ('status', models.BooleanField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whatsnew_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whatsnew_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsnew',
            },
        ),
        migrations.AddField(
            model_name='detailwhatsnew',
            name='whatsnew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='whatsnew.Whatsnew'),
        ),
    ]
