# Generated by Django 2.0.4 on 2018-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideraboutus',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/slider'),
        ),
    ]
