# Generated by Django 2.0.4 on 2018-05-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourservices', '0002_auto_20180508_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservicedetail',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='ourservicedetail',
            name='our_services',
        ),
    ]
