# Generated by Django 2.0.4 on 2018-05-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservices', '0003_auto_20180521_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservicedetail',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
