# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCotact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('address', models.TextField(blank=True, null=True)),
                ('telphone', models.CharField(max_length=225)),
                ('fax', models.CharField(max_length=225)),
                ('status', models.BooleanField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ourcotact_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ourcotact_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'our_contact',
            },
        ),
        migrations.CreateModel(
            name='Sosmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/sosmed')),
                ('caption', models.CharField(blank=True, max_length=225, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('OurCotact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourcontact.OurCotact')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sosmed_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sosmed_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detail_galery',
            },
        ),
    ]
