# Generated by Django 2.0.4 on 2018-05-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourclients', '0002_auto_20180508_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourclient',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
